// --- 1. CONNECTIONS ---
const SUPABASE_URL = 'https://uvhczzpqqppnlgzideul.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aGN6enBxcHBwbmxnemlkZXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NjE0MjEsImV4cCI6MjA4NjIzNzQyMX0.TSM4OjP1wfHxlgNWIrzfXW0-PrIIMsCEVd7n6RhKPcM';
const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

// --- 2. SMART PROJECT ANALYZER (GEMINI AI) ---
async function analyzeProjectAI() {
    const text = document.getElementById("topicInput").value;
        const output = document.getElementById("ai-output");
            const apiKey = CONFIG.GEMINI_KEY; 

                if (!text) return alert("Paste a project description first!");
                    output.innerHTML = "<em>AI is researching...</em>";

                        try {
                                const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
                                            method: "POST",
                                                        headers: { "Content-Type": "application/json" },
                                                                    body: JSON.stringify({
                                                                                    contents: [{ parts: [{ text: `Act as a crypto researcher. Analyze this project info: ${text}. Give me the category and 3 hard-hitting host questions. Format as JSON: {"category": "...", "questions": ["...", "...", "..."]}` }] }]
                                                                                                })
                                                                                                        });
                                                                                                                
                                                                                                                        const data = await response.json();
                                                                                                                                const rawText = data.candidates[0].content.parts[0].text;
                                                                                                                                        const cleanJSON = JSON.parse(rawText.replace(/```json|```/g, "").trim());

                                                                                                                                                output.innerHTML = `<strong>${cleanJSON.category}</strong><ul>` + 
                                                                                                                                                            cleanJSON.questions.map(q => `<li>${q} <button onclick="addToQueue('${q}')">+</button></li>`).join('') + `</ul>`;
                                                                                                                                                                } catch (e) { 
                                                                                                                                                                        output.innerHTML = "AI Error. Check your Gemini Key in config.js";
                                                                                                                                                                            }
                                                                                                                                                                            }

                                                                                                                                                                            // --- 3. VIRAL QUESTION GENERATOR (NEW) ---
                                                                                                                                                                            function getViral() {
                                                                                                                                                                                const viralPacks = [
                                                                                                                                                                                        "What is one thing your competitors are doing better than you?",
                                                                                                                                                                                                "If the market crashes tomorrow, why does this project survive?",
                                                                                                                                                                                                        "Explain the tokenomics to me like I am five years old.",
                                                                                                                                                                                                                "What is the 'final boss' obstacle for this project this year?",
                                                                                                                                                                                                                        "🔥 Hot Take: Is this project actually solving a problem or just hype?"
                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                const randomQ = viralPacks[Math.floor(Math.random() * viralPacks.length)];
                                                                                                                                                                                                                                    addToQueue(randomQ); // This puts it in your live list
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    // --- 4. SESSION RECAP BUILDER (NEW) ---
                                                                                                                                                                                                                                    function generateRecap() {
                                                                                                                                                                                                                                        const list = document.getElementById("questionList").innerText;
                                                                                                                                                                                                                                            if (!list) return alert("No questions to recap!");
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    const recap = `🚀 ZEIROKO SESSION RECAP\n\nKey Questions Covered:\n${list}\n\nHosted via @ZEIROKO_Toolkit`;
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            navigator.clipboard.writeText(recap);
                                                                                                                                                                                                                                                                alert("Recap copied to clipboard! Paste it on X.");
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                // --- 5. LIVE SPACE TOOLS ---
                                                                                                                                                                                                                                                                function addToQueue(q) {
                                                                                                                                                                                                                                                                    const list = document.getElementById("questionList");
                                                                                                                                                                                                                                                                        const li = document.createElement("li");
                                                                                                                                                                                                                                                                            li.innerHTML = `<span class="gold-dot"></span> ${q}`;
                                                                                                                                                                                                                                                                                list.appendChild(li);
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                function addQuestion() {
                                                                                                                                                                                                                                                                                    const q = document.getElementById("questionInput").value;
                                                                                                                                                                                                                                                                                        if(q) { addToQueue(q); document.getElementById("questionInput").value = ""; }
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                        function nextStage() {
                                                                                                                                                                                                                                                                                            const steps = document.querySelectorAll('.step');
                                                                                                                                                                                                                                                                                                for (let i = 0; i < steps.length; i++) {
                                                                                                                                                                                                                                                                                                        if (steps[i].classList.contains('active') && i < steps.length - 1) {
                                                                                                                                                                                                                                                                                                                    steps[i].classList.remove('active');
                                                                                                                                                                                                                                                                                                                                steps[i+1].classList.add('active');
                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        let seconds = 0;
                                                                                                                                                                                                                                                                                                                                                        function startTimer() {
                                                                                                                                                                                                                                                                                                                                                            setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                    seconds++;
                                                                                                                                                                                                                                                                                                                                                                            let min = Math.floor(seconds / 60);
                                                                                                                                                                                                                                                                                                                                                                                    let sec = seconds % 60;
                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("timer").innerText = `${String(min).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
                                                                                                                                                                                                                                                                                                                                                                                                }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                }
